export let cars = [{model: 'Lada', yearOfIssue: 2010, powerful: 98, colour: 'green', isCrashed: false},
  {model: 'Toyota', yearOfIssue: 2009, powerful: 112, colour: 'yellow', isCrashed: true},
  {model: 'Volvo', yearOfIssue: 2008, powerful: 134, colour: 'red', isCrashed: false},
  {model: 'Volkswagen', yearOfIssue: 2007, powerful: 167, colour: 'blue', isCrashed: false},
  {model: 'BMW', yearOfIssue: 2006, powerful: 176, colour: 'grey', isCrashed: true},
  {model: 'Ford', yearOfIssue: 2005, powerful: 134, colour: 'pink', isCrashed: false},
  {model: 'Mazda', yearOfIssue: 2004, powerful: 167, colour: 'black', isCrashed: false},
  {model: 'KIA', yearOfIssue: 2003, powerful: 174, colour: 'white', isCrashed: false},
  {model: 'Renault', yearOfIssue: 2002, powerful: 131, colour: 'brown', isCrashed: false},
  {model: 'Audi', yearOfIssue: 2001, powerful: 145, colour: 'black', isCrashed: true}];
