export let cars = [{model : 'Lada',      yearOfIssue : 2010,  powerful : 98,  colour : 'green'},
  {model : 'Toyota',     yearOfIssue : 2009,  powerful : 112, colour : 'yellow'},
  {model : 'Volvo',      yearOfIssue : 2008,  powerful : 134, colour : 'red'},
  {model : 'Volkswagen', yearOfIssue : 2007,  powerful : 167, colour : 'blue'},
  {model : 'BMW',        yearOfIssue : 2006,  powerful : 176, colour : 'grey'},
  {model : 'Ford',       yearOfIssue : 2005,  powerful : 134, colour : 'pink'},
  {model : 'Mazda',      yearOfIssue : 2004,  powerful : 167, colour : 'black'},
  {model : 'KIA',        yearOfIssue : 2003,  powerful : 174, colour : 'white'},
  {model : 'Renault',    yearOfIssue : 2002,  powerful : 131, colour : 'brown'},
  {model : 'Audi',       yearOfIssue : 2001,  powerful : 145, colour : 'black'}]
